# =========================
# Stage 1 → Build Stage
# =========================

FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

# =========================
# Stage 2 → Runtime Stage
# =========================

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Define build arguments
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG JWT_SECRET
ARG JWT_EXPIRATION
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_PHONE_NUMBER
ARG TWILIO_MESSAGING_SID
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG SPRING_MAIL_HOST
ARG SPRING_MAIL_PORT
ARG GEMINI_API_KEY
ARG GEMINI_API_URL
ARG OPENAI_API_KEY
ARG OPENAI_MODEL
ARG OPENAI_API_URL
ARG HUGGINGFACE_API_TOKEN
ARG HUGGINGFACE_API_URL
ARG HUGGINGFACE_MODEL_ID
ARG OLLAMA_BASE_URL
ARG OLLAMA_MODEL

# Set environment variables
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRATION=$JWT_EXPIRATION
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
ENV TWILIO_MESSAGING_SID=$TWILIO_MESSAGING_SID
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV SPRING_MAIL_HOST=$SPRING_MAIL_HOST
ENV SPRING_MAIL_PORT=$SPRING_MAIL_PORT
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV GEMINI_API_URL=$GEMINI_API_URL
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_MODEL=$OPENAI_MODEL
ENV OPENAI_API_URL=$OPENAI_API_URL
ENV HUGGINGFACE_API_TOKEN=$HUGGINGFACE_API_TOKEN
ENV HUGGINGFACE_API_URL=$HUGGINGFACE_API_URL
ENV HUGGINGFACE_MODEL_ID=$HUGGINGFACE_MODEL_ID
ENV OLLAMA_BASE_URL=$OLLAMA_BASE_URL
ENV OLLAMA_MODEL=$OLLAMA_MODEL

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
