spring.application.name=genmillenauts


spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

twilio.accountSid=${TWILIO_ACCOUNT_SID}
twilio.authToken=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER}
twilio.messagingSid=${TWILIO_MESSAGING_SID}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

openai.api.key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL}

huggingface.api.token=${HUGGINGFACE_API_TOKEN}
huggingface.api.url=${HUGGINGFACE_API_URL}
huggingface.model.id=${HUGGINGFACE_MODEL_ID}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL}