spring.application.name=genmillenauts

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

info.app.name=ProofTracker
info.app.version=1.0.0

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

twilio.accountSid=${TWILIO_ACCOUNT_SID}
twilio.authToken=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_PHONE_NUMBER}
twilio.messagingSid=${TWILIO_MESSAGING_SID}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}
gemini.model=gemini-2.5-flash

openai.api.key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL}
openai.api.url=${OPENAI_API_URL}
OPENAI_MODEL=gpt-5-nano


huggingface.api.token=${HUGGINGFACE_API_TOKEN}
huggingface.api.url=${HUGGINGFACE_API_URL}
huggingface.model.id=${HUGGINGFACE_MODEL_ID}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL}


ai.azure.endpoint=${AI_AZURE_ENDPOINT}
ai.azure.api.key=${AI_AZURE_API_KEY}
ai.azure.deployment=${AI_AZURE_DEPLOYMENT}
ai.provider=azure

# AI Provider Selection
